#!/usr/bin/env python3
"""
WalletWise AI Backend - Interactive Test Runner
Provides a menu-driven interface to test different aspects of the API
"""

import requests
import json
import time
import sys
from typing import Dict, Any

BASE_URL = "http://127.0.0.1:8000"

class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    BOLD = '\033[1m'
    END = '\033[0m'

def print_colored(text: str, color: str = Colors.END):
    """Print colored text"""
    print(f"{color}{text}{Colors.END}")

def check_server():
    """Check if the server is running"""
    try:
        response = requests.get(f"{BASE_URL}/docs", timeout=5)
        return response.status_code in [200, 404]
    except:
        return False

def test_parse_text():
    """Interactive text parsing test"""
    print_colored("\n🧪 TRANSACTION TEXT PARSING TEST", Colors.BOLD)
    print("="*50)
    
    sample_texts = [
        "You spent Rs.500 at Zomato on 2024-01-15",
        "INR 1200 debited. Paid to Swiggy Instamart on 2024-01-16",
        "Rs.2500 paid to H&M via UPI Ref: 123456789",
        "Amount Rs.150 spent at Apollo Pharmacy on 15-Jan-24"
    ]
    
    print("Choose a sample SMS or enter your own:")
    for i, text in enumerate(sample_texts, 1):
        print(f"{i}. {text}")
    print("5. Enter custom SMS text")
    
    choice = input("\nEnter choice (1-5): ").strip()
    
    if choice in ['1', '2', '3', '4']:
        text = sample_texts[int(choice) - 1]
    elif choice == '5':
        text = input("Enter SMS text: ").strip()
    else:
        print_colored("Invalid choice", Colors.RED)
        return
    
    print(f"\n📱 Testing: {text}")
    
    try:
        response = requests.post(f"{BASE_URL}/parse-text/", json={"text": text})
        if response.status_code == 200:
            result = response.json()
            print_colored("✅ SUCCESS!", Colors.GREEN)
            print(f"🏪 Merchant: {result.get('recipientName')}")
            print(f"💰 Amount: Rs.{result.get('amount')}")
            print(f"📤 Type: {'Debit' if result.get('isDebit') else 'Credit'}")
            print(f"⏰ Time: {result.get('timestamp')}")
        else:
            print_colored(f"❌ Error: {response.text}", Colors.RED)
    except Exception as e:
        print_colored(f"❌ Connection error: {e}", Colors.RED)

def test_categorization():
    """Interactive categorization test"""
    print_colored("\n🧠 AI CATEGORIZATION TEST", Colors.BOLD)
    print("="*50)
    
    cached_merchants = ["Zomato", "Swiggy Instamart", "H&M", "Apollo Pharmacy", "IRCTC", "Pratik Jain"]
    new_merchants = ["Netflix", "Uber", "BookMyShow", "Dominos", "BigBasket"]
    
    print("Choose merchant type:")
    print("1. Test cached merchants (should return from database)")
    print("2. Test new merchants (should use AI prediction)")
    print("3. Enter custom merchant name")
    
    choice = input("\nEnter choice (1-3): ").strip()
    
    if choice == '1':
        print("\nCached merchants:")
        for i, merchant in enumerate(cached_merchants, 1):
            print(f"{i}. {merchant}")
        merchant_choice = input(f"Choose merchant (1-{len(cached_merchants)}): ").strip()
        try:
            merchant = cached_merchants[int(merchant_choice) - 1]
        except:
            print_colored("Invalid choice", Colors.RED)
            return
    elif choice == '2':
        print("\nNew merchants:")
        for i, merchant in enumerate(new_merchants, 1):
            print(f"{i}. {merchant}")
        merchant_choice = input(f"Choose merchant (1-{len(new_merchants)}): ").strip()
        try:
            merchant = new_merchants[int(merchant_choice) - 1]
        except:
            print_colored("Invalid choice", Colors.RED)
            return
    elif choice == '3':
        merchant = input("Enter merchant name: ").strip()
    else:
        print_colored("Invalid choice", Colors.RED)
        return
    
    print(f"\n🏪 Testing categorization for: {merchant}")
    
    try:
        response = requests.post(f"{BASE_URL}/get-category/", json={"name": merchant})
        if response.status_code == 200:
            result = response.json()
            print_colored("✅ SUCCESS!", Colors.GREEN)
            print(f"🏪 Merchant: {result.get('receiver_name')}")
            print(f"📂 Category: {result.get('category')}")
            print(f"🔍 Source: {result.get('source')}")
            
            if result.get('source') == 'User History (Cache)':
                print_colored("💾 Retrieved from cached user history", Colors.BLUE)
            else:
                print_colored("🤖 Generated by AI prediction", Colors.YELLOW)
        else:
            print_colored(f"❌ Error: {response.text}", Colors.RED)
    except Exception as e:
        print_colored(f"❌ Connection error: {e}", Colors.RED)

def test_learning():
    """Interactive learning system test"""
    print_colored("\n🎓 LEARNING SYSTEM TEST", Colors.BOLD)
    print("="*50)
    
    print("This will teach the system a new category and verify learning.")
    
    merchant = input("Enter merchant name: ").strip()
    if not merchant:
        print_colored("Merchant name cannot be empty", Colors.RED)
        return
    
    categories = ['Food', 'Groceries', 'Clothes', 'Health', 'Personal', 'Travelling', 'Bills', 'Entertainment', 'Other']
    print("\nAvailable categories:")
    for i, cat in enumerate(categories, 1):
        print(f"{i}. {cat}")
    
    cat_choice = input(f"\nChoose category (1-{len(categories)}): ").strip()
    try:
        category = categories[int(cat_choice) - 1]
    except:
        print_colored("Invalid choice", Colors.RED)
        return
    
    print(f"\n📚 Teaching: {merchant} → {category}")
    
    # Step 1: Get initial prediction
    try:
        response = requests.post(f"{BASE_URL}/get-category/", json={"name": merchant})
        if response.status_code == 200:
            initial = response.json()
            print(f"🔍 Initial prediction: {initial.get('category')} ({initial.get('source')})")
    except:
        print_colored("Could not get initial prediction", Colors.YELLOW)
    
    # Step 2: Teach the system
    try:
        correction_data = {"receiver_name": merchant, "confirmed_category": category}
        response = requests.post(f"{BASE_URL}/confirm-category/", json=correction_data)
        if response.status_code == 200:
            result = response.json()
            print_colored(f"✅ {result.get('message')}", Colors.GREEN)
        else:
            print_colored(f"❌ Teaching failed: {response.text}", Colors.RED)
            return
    except Exception as e:
        print_colored(f"❌ Teaching error: {e}", Colors.RED)
        return
    
    # Step 3: Verify learning
    print("\n🔍 Verifying learning...")
    try:
        response = requests.post(f"{BASE_URL}/get-category/", json={"name": merchant})
        if response.status_code == 200:
            learned = response.json()
            print(f"📂 After learning: {learned.get('category')} ({learned.get('source')})")
            
            if (learned.get('source') == 'User History (Cache)' and 
                learned.get('category') == category):
                print_colored("🎉 Learning successful! System remembered the correction.", Colors.GREEN)
            else:
                print_colored("❌ Learning failed - system did not remember", Colors.RED)
        else:
            print_colored(f"❌ Verification failed: {response.text}", Colors.RED)
    except Exception as e:
        print_colored(f"❌ Verification error: {e}", Colors.RED)

def run_all_tests():
    """Run all comprehensive tests"""
    print_colored("\n🚀 RUNNING ALL COMPREHENSIVE TESTS", Colors.BOLD)
    print("="*50)
    
    print("Running comprehensive test suite...")
    try:
        import subprocess
        result = subprocess.run([sys.executable, "test_comprehensive.py"], 
                              capture_output=True, text=True, cwd=".")
        
        if result.returncode == 0:
            print_colored("✅ All tests completed successfully!", Colors.GREEN)
            print(result.stdout)
        else:
            print_colored("❌ Some tests failed:", Colors.RED)
            print(result.stdout)
            print(result.stderr)
    except FileNotFoundError:
        print_colored("❌ test_comprehensive.py not found. Please ensure it exists in the current directory.", Colors.RED)
    except Exception as e:
        print_colored(f"❌ Error running tests: {e}", Colors.RED)

def main_menu():
    """Display main menu and handle user choices"""
    while True:
        print_colored("\n🤖 WalletWise AI Backend - Interactive Test Runner", Colors.BOLD)
        print("="*60)
        
        # Check server status
        if check_server():
            print_colored("🟢 Server Status: Online", Colors.GREEN)
        else:
            print_colored("🔴 Server Status: Offline", Colors.RED)
            print_colored("Please start the server first: python start_server.py", Colors.YELLOW)
            print()
        
        print("\nChoose a test to run:")
        print("1. 📱 Test Transaction Text Parsing")
        print("2. 🧠 Test AI Categorization")
        print("3. 🎓 Test Learning System")
        print("4. 🚀 Run All Comprehensive Tests")
        print("5. 📖 Open API Documentation")
        print("6. ❌ Exit")
        
        choice = input("\nEnter your choice (1-6): ").strip()
        
        if choice == '1':
            test_parse_text()
        elif choice == '2':
            test_categorization()
        elif choice == '3':
            test_learning()
        elif choice == '4':
            run_all_tests()
        elif choice == '5':
            print_colored(f"\n📖 Opening API documentation in browser...", Colors.BLUE)
            print(f"Swagger UI: {BASE_URL}/docs")
            print(f"ReDoc: {BASE_URL}/redoc")
            import webbrowser
            try:
                webbrowser.open(f"{BASE_URL}/docs")
            except:
                print("Please open the URL manually in your browser.")
        elif choice == '6':
            print_colored("\n👋 Goodbye! Thanks for testing WalletWise AI Backend!", Colors.BLUE)
            break
        else:
            print_colored("Invalid choice. Please enter 1-6.", Colors.RED)
        
        input("\nPress Enter to continue...")

if __name__ == "__main__":
    try:
        main_menu()
    except KeyboardInterrupt:
        print_colored("\n\n👋 Test runner interrupted. Goodbye!", Colors.YELLOW)